version: "3.1"
services:
  tamagotchi-db:
    container_name: tamagotchi-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Mahacskin13!
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    networks:
      - docker-tamagotchi
networks:
  docker-tamagotchi:
